version: '3.3'
services:
  pg:
    container_name: ms25-db
    image: postgres
    ports:
      - "5439:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ms25
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms25

volumes:
  db_data: { }
